added player files, environment files, Controller, Service, Repo
T-Kutzner/capstone-mastermind pull request #10
Opened 2022-03-31 14:55 UTC by T-Kutzner

2022-03-31 20:17 UTC, gossie requested changes
The issues with the endless recursion and the `@DeleteMapping` need to be fixed before approval, because they would cause errors.
The other issues are more or less optional.

2022-03-31 20:17 UTC, gossie commented on backend/src/main/java/de/tk/mastermind/repositories/PlayerRepository.java
> +    Optional<Player> findById(String id);
You don't need to define that method. It is already present in the `MongoRepository`.

2022-04-01 10:41 UTC, T-Kutzner commented
Please check fixed issues

2022-04-01 11:17 UTC, gossie approved these changes

2022-04-01 11:45 UTC, merged